import type { Metadata } from "next";
import {Poppins} from "next/font/google"
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css'

// import {Montserrat} from "next/font/ggogle";
import HeadLine from "@/components/Headline"
import Footer from "@/components/Footer";
import Script from "next/script";
const Font = Poppins ({
  subsets : ['latin'],
  weight : ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"]
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={Font.className}     
      >
        <HeadLine/>
        {children}
        <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" />
        <Footer/>
       
      </body>
    </html>
  );
}
